<?php

return [
    [
        'key' => 'public.home',
        'title_ro' => 'Pagina principală',
        'title_en' => 'Homepage',
        'description_ro' => 'Prezentarea YouGo, cum funcționează și ce face produsul.',
        'description_en' => 'YouGo overview, how it works and what the product does.',
        'href' => '/',
        'surface' => 'public',
        'requires_auth' => false,
        'keywords' => ['home', 'homepage', 'acasa', 'principal'],
    ],
    [
        'key' => 'public.pricing',
        'title_ro' => 'Prețuri',
        'title_en' => 'Pricing',
        'description_ro' => 'Planuri, limite și canale incluse.',
        'description_en' => 'Plans, limits and included channels.',
        'href' => '/#pricing',
        'surface' => 'public',
        'requires_auth' => false,
        'keywords' => ['pricing', 'preturi', 'prețuri', 'plan', 'cost', 'abonament'],
    ],
    [
        'key' => 'public.register',
        'title_ro' => 'Creează cont',
        'title_en' => 'Create account',
        'description_ro' => 'Înregistrare pentru a începe configurarea YouGo.',
        'description_en' => 'Registration to start setting up YouGo.',
        'href' => '/register',
        'surface' => 'public',
        'requires_auth' => false,
        'keywords' => ['register', 'start', 'cont', 'creeaza', 'înregistrare', 'inregistrare'],
    ],
    [
        'key' => 'public.login',
        'title_ro' => 'Autentificare',
        'title_en' => 'Login',
        'description_ro' => 'Intră în contul YouGo.',
        'description_en' => 'Sign in to YouGo.',
        'href' => '/login',
        'surface' => 'public',
        'requires_auth' => false,
        'keywords' => ['login', 'autentificare', 'conectare', 'intra'],
    ],
    [
        'key' => 'public.industries',
        'title_ro' => 'Industrii',
        'title_en' => 'Industries',
        'description_ro' => 'Exemple de folosire YouGo pe tipuri de business.',
        'description_en' => 'Examples of how YouGo works by business type.',
        'href' => '/industries/salon-beauty',
        'surface' => 'public',
        'requires_auth' => false,
        'keywords' => ['industries', 'industrii', 'salon', 'clinica', 'clinic', 'service auto'],
    ],
    [
        'key' => 'dashboard.overview',
        'title_ro' => 'Dashboard',
        'title_en' => 'Dashboard',
        'description_ro' => 'Rezumat pentru conversații, programări și activitate.',
        'description_en' => 'Summary for conversations, bookings and activity.',
        'href' => '/dashboard',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['dashboard', 'overview', 'prezentare', 'rezumat'],
    ],
    [
        'key' => 'dashboard.onboarding',
        'title_ro' => 'Configurare inițială',
        'title_en' => 'Initial setup',
        'description_ro' => 'Checklist pentru configurarea businessului.',
        'description_en' => 'Checklist for setting up the business.',
        'href' => '/dashboard/onboarding',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['onboarding', 'configurare', 'setup', 'initial'],
    ],
    [
        'key' => 'dashboard.bookings',
        'title_ro' => 'Programări',
        'title_en' => 'Bookings',
        'description_ro' => 'Cererile de programare create de AI și statusul lor.',
        'description_en' => 'AI-created booking requests and their status.',
        'href' => '/dashboard/bookings',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['bookings', 'programari', 'programări', 'appointments', 'calendar', 'rezervari'],
    ],
    [
        'key' => 'dashboard.conversations',
        'title_ro' => 'Conversații',
        'title_en' => 'Conversations',
        'description_ro' => 'Conversațiile gestionate de asistent.',
        'description_en' => 'Conversations handled by the assistant.',
        'href' => '/dashboard/conversations',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['conversations', 'conversatii', 'conversații', 'chat history', 'transcript'],
    ],
    [
        'key' => 'dashboard.widget',
        'title_ro' => 'Chat / Widget',
        'title_en' => 'Chat / Widget',
        'description_ro' => 'Previzualizare, setări widget și codul de instalare.',
        'description_en' => 'Preview, widget settings and install snippet.',
        'href' => '/dashboard/widget',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['widget', 'snippet', 'install', 'instalare', 'cod', 'chat'],
    ],
    [
        'key' => 'dashboard.services',
        'title_ro' => 'Servicii',
        'title_en' => 'Services',
        'description_ro' => 'Servicii, prețuri, durată și capacitate.',
        'description_en' => 'Services, prices, duration and capacity.',
        'href' => '/dashboard/services',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['services', 'servicii', 'preturi', 'prețuri', 'durata'],
    ],
    [
        'key' => 'dashboard.locations',
        'title_ro' => 'Locații și orar',
        'title_en' => 'Locations and hours',
        'description_ro' => 'Adrese, locații și program de lucru.',
        'description_en' => 'Addresses, locations and opening hours.',
        'href' => '/dashboard/locations',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['locations', 'locatii', 'locații', 'orar', 'hours', 'program'],
    ],
    [
        'key' => 'dashboard.staff',
        'title_ro' => 'Echipă',
        'title_en' => 'Team',
        'description_ro' => 'Membrii echipei și asignările pe servicii/locații.',
        'description_en' => 'Team members and service/location assignments.',
        'href' => '/dashboard/staff',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['staff', 'team', 'echipa', 'echipă', 'angajati'],
    ],
    [
        'key' => 'dashboard.settings',
        'title_ro' => 'Setări',
        'title_en' => 'Settings',
        'description_ro' => 'Cont, business, notificări și limbă.',
        'description_en' => 'Account, business, notifications and language.',
        'href' => '/dashboard/settings',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['settings', 'setari', 'setări', 'notifications', 'notificari'],
    ],
    [
        'key' => 'dashboard.billing',
        'title_ro' => 'Facturare',
        'title_en' => 'Billing',
        'description_ro' => 'Plan curent, limite și utilizare.',
        'description_en' => 'Current plan, limits and usage.',
        'href' => '/dashboard/billing',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['billing', 'facturare', 'plan', 'usage', 'utilizare', 'limite'],
    ],
    [
        'key' => 'dashboard.ai-settings',
        'title_ro' => 'Setări AI',
        'title_en' => 'AI Settings',
        'description_ro' => 'Identitate, ton, instrucțiuni și comportament AI.',
        'description_en' => 'AI identity, tone, instructions and behavior.',
        'href' => '/dashboard/ai-settings',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['ai settings', 'setari ai', 'setări ai', 'instructiuni', 'prompt', 'context'],
    ],
    [
        'key' => 'dashboard.whatsapp',
        'title_ro' => 'WhatsApp',
        'title_en' => 'WhatsApp',
        'description_ro' => 'Secțiune pregătită pentru WhatsApp AI, momentan planned.',
        'description_en' => 'Prepared area for WhatsApp AI, currently planned.',
        'href' => '/dashboard/whatsapp',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['whatsapp', 'wa'],
    ],
    [
        'key' => 'dashboard.voice-calls',
        'title_ro' => 'Apeluri telefonice',
        'title_en' => 'Voice calls',
        'description_ro' => 'Secțiune pregătită pentru Phone AI, momentan planned.',
        'description_en' => 'Prepared area for Phone AI, currently planned.',
        'href' => '/dashboard/voice-calls',
        'surface' => 'dashboard',
        'requires_auth' => true,
        'keywords' => ['phone', 'telefon', 'apeluri', 'voice', 'calls', 'telnyx'],
    ],
];
