<?php

return [
    'free' => [
        'key' => 'free',
        'name' => 'Free',
        'price_label' => '0 RON',
        'description' => 'Test the AI receptionist with the full basic flow, limited usage.',
        'monthly_conversations' => 50,
        'monthly_ai_messages' => 100,
        'monthly_bookings' => 10,
        'widgets_enabled' => true,
        'whatsapp_enabled' => false,
        'phone_enabled' => false,
        'channels' => [
            'Chat + Voice',
        ],
        'features' => [
            'Chat + Voice',
            'AI booking requests',
            'Availability checks',
            'Dashboard access',
        ],
        'limitations' => [
            'No WhatsApp',
            'No phone calls',
            'Limited usage',
        ],
    ],
    'website_chat' => [
        'key' => 'website_chat',
        'name' => 'Website Chat',
        'price_label' => '149 RON/lună',
        'monthly_conversations' => 500,
        'monthly_ai_messages' => 2000,
        'monthly_bookings' => 200,
        'monthly_whatsapp_messages' => 0,
        'monthly_phone_minutes' => 0,
        'widgets_enabled' => true,
        'whatsapp_enabled' => false,
        'phone_enabled' => false,
        'ai_bookings_enabled' => true,
        'recommended' => false,
        'channels' => [
            'Chat + Voice',
        ],
        'features' => [
            'Chat + Voice',
            'Programări AI',
            'Dashboard',
            'Notificări email pentru programări',
        ],
        'short_description_ro' => 'AI pe site pentru conversații și programări. Trimite notificări email pentru cererile noi.',
        'short_description_en' => 'AI on your website for conversations and bookings. Sends email notifications for new requests.',
        'phone_minutes_label' => '—',
    ],
    'chat_whatsapp' => [
        'key' => 'chat_whatsapp',
        'name' => 'Chat + WhatsApp',
        'price_label' => '299 RON/lună',
        'monthly_conversations' => 1000,
        'monthly_ai_messages' => 4000,
        'monthly_bookings' => 400,
        'monthly_whatsapp_messages' => 500,
        'monthly_phone_minutes' => 0,
        'widgets_enabled' => true,
        'whatsapp_enabled' => true,
        'phone_enabled' => false,
        'ai_bookings_enabled' => true,
        'recommended' => false,
        'channels' => [
            'Chat + Voice',
            'WhatsApp',
        ],
        'features' => [
            'Chat + Voice',
            'WhatsApp',
            'Programări AI',
            'Dashboard',
            'Notificări email pentru programări',
        ],
        'short_description_ro' => 'AI pe site și WhatsApp pentru răspunsuri rapide. Trimite notificări email pentru cererile noi.',
        'short_description_en' => 'AI on your website and WhatsApp for faster replies. Sends email notifications for new requests.',
        'phone_minutes_label' => '—',
    ],
    'voice_starter' => [
        'key' => 'voice_starter',
        'name' => 'Voice Starter',
        'price_label' => '599 RON/lună',
        'monthly_conversations' => 1500,
        'monthly_ai_messages' => 6000,
        'monthly_bookings' => 600,
        'monthly_whatsapp_messages' => 750,
        'monthly_phone_minutes' => 300,
        'widgets_enabled' => true,
        'whatsapp_enabled' => true,
        'phone_enabled' => true,
        'ai_bookings_enabled' => true,
        'recommended' => true,
        'channels' => [
            'Chat + Voice',
            'WhatsApp',
            'Telefon AI',
        ],
        'features' => [
            'Telefon AI',
            'Chat + Voice',
            'WhatsApp',
            'Programări AI',
            'Dashboard',
            'Notificări email pentru programări',
        ],
        'short_description_ro' => 'Recepționer AI complet pentru afaceri mici. Trimite notificări email pentru cererile noi.',
        'short_description_en' => 'Complete AI receptionist for small businesses. Sends email notifications for new requests.',
        'phone_minutes_label' => '300 min',
    ],
    'voice_growth' => [
        'key' => 'voice_growth',
        'name' => 'Voice Growth',
        'price_label' => '999 RON/lună',
        'monthly_conversations' => 3000,
        'monthly_ai_messages' => 12000,
        'monthly_bookings' => 1200,
        'monthly_whatsapp_messages' => 1500,
        'monthly_phone_minutes' => 1000,
        'widgets_enabled' => true,
        'whatsapp_enabled' => true,
        'phone_enabled' => true,
        'ai_bookings_enabled' => true,
        'recommended' => false,
        'channels' => [
            'Chat + Voice',
            'WhatsApp',
            'Telefon AI',
        ],
        'features' => [
            'Telefon AI',
            'Chat + Voice',
            'WhatsApp',
            'Programări AI',
            'Dashboard',
            'Notificări email pentru programări',
        ],
        'short_description_ro' => 'Recepționer AI pentru businessuri cu volum mai mare. Trimite notificări email pentru cererile noi.',
        'short_description_en' => 'AI receptionist for businesses with higher volume. Sends email notifications for new requests.',
        'phone_minutes_label' => '1000 min',
    ],
    'voice_pro' => [
        'key' => 'voice_pro',
        'name' => 'Voice Pro',
        'price_label' => '2.499 RON/lună',
        'monthly_conversations' => 8000,
        'monthly_ai_messages' => 30000,
        'monthly_bookings' => 3000,
        'monthly_whatsapp_messages' => 5000,
        'monthly_phone_minutes' => 3000,
        'widgets_enabled' => true,
        'whatsapp_enabled' => true,
        'phone_enabled' => true,
        'ai_bookings_enabled' => true,
        'recommended' => false,
        'channels' => [
            'Chat + Voice',
            'WhatsApp',
            'Telefon AI',
        ],
        'features' => [
            'Telefon AI',
            'Chat + Voice',
            'WhatsApp',
            'Programări AI',
            'Dashboard',
            'Notificări email pentru programări',
        ],
        'short_description_ro' => 'Recepționer AI pentru echipe ocupate și volum mare. Trimite notificări email pentru cererile noi.',
        'short_description_en' => 'AI receptionist for busy teams and high volume. Sends email notifications for new requests.',
        'phone_minutes_label' => '3000 min',
    ],
];
