<?php

return [
    'free' => [
        'key' => 'free',
        'name' => 'Free',
        'price_label' => '0 RON',
        'description' => 'Test the AI receptionist with the full basic flow, limited usage.',
        'monthly_conversations' => 50,
        'monthly_ai_messages' => 100,
        'monthly_bookings' => 10,
        'widgets_enabled' => true,
        'whatsapp_enabled' => false,
        'phone_enabled' => false,
        'channels' => [
            'Website chat',
        ],
        'features' => [
            'Website AI chat widget',
            'AI booking requests',
            'Availability checks',
            'Dashboard access',
        ],
        'limitations' => [
            'No WhatsApp',
            'No phone calls',
            'Limited usage',
        ],
    ],
    'connect' => [
        'key' => 'connect',
        'name' => 'Connect',
        'price_label' => '299 RON/lună',
        'description' => 'For businesses that want website chat and WhatsApp conversations in one assistant.',
        'monthly_conversations' => 500,
        'monthly_ai_messages' => 2000,
        'monthly_bookings' => 200,
        'monthly_whatsapp_messages' => 500,
        'widgets_enabled' => true,
        'whatsapp_enabled' => true,
        'phone_enabled' => false,
        'recommended' => true,
        'channels' => [
            'Website chat',
            'WhatsApp',
        ],
        'features' => [
            'Website AI chat widget',
            'AI booking requests',
            'Availability checks',
            'Dashboard access',
            'Email booking notifications',
            'WhatsApp assistant',
        ],
        'limitations' => [
            'No phone calls included',
        ],
    ],
    'voice' => [
        'key' => 'voice',
        'name' => 'Voice',
        'price_label' => '799 RON/lună',
        'description' => 'For businesses that want chat, WhatsApp and AI phone answering.',
        'monthly_conversations' => 1500,
        'monthly_ai_messages' => 7500,
        'monthly_bookings' => 750,
        'monthly_whatsapp_messages' => 1000,
        'phone_enabled' => true,
        'phone_billing_label' => 'Telefon AI calculat la minut',
        'phone_minute_price_label' => '2.50 RON/minut',
        'widgets_enabled' => true,
        'whatsapp_enabled' => true,
        'channels' => [
            'Website chat',
            'WhatsApp',
            'Phone AI',
        ],
        'features' => [
            'Website AI chat widget',
            'AI booking requests',
            'Availability checks',
            'Dashboard access',
            'Email booking notifications',
            'WhatsApp assistant',
            'AI phone answering',
        ],
        'limitations' => [
            'Phone minutes are billed separately',
        ],
    ],
    'enterprise' => [
        'key' => 'enterprise',
        'name' => 'Enterprise',
        'price_label' => 'Custom',
        'description' => 'For multi-location businesses, high volume usage and custom integrations.',
        'monthly_conversations' => null,
        'monthly_ai_messages' => null,
        'monthly_bookings' => null,
        'widgets_enabled' => true,
        'whatsapp_enabled' => true,
        'phone_enabled' => true,
        'contact_sales' => true,
        'channels' => [
            'Website chat',
            'WhatsApp',
            'Phone AI',
            'Custom integrations',
        ],
        'features' => [
            'Website AI chat widget',
            'AI booking requests',
            'Availability checks',
            'Dashboard access',
            'Email booking notifications',
            'WhatsApp assistant',
            'AI phone answering',
            'Custom usage limits',
            'Multi-location support',
            'Advanced setup',
            'Custom integrations',
        ],
        'limitations' => [],
    ],
];
